/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 119e09066f69a33ebfbd9e6b86c83aee)
interface __BaseEnv_Env {
	RESEND_FROM_EMAIL: "Yunnan Unfolded <enquiries@yunnanunfolded.com>";
	INQUIRY_TO_EMAIL: "hello@yunnanunfolded.com";
	ALLOWED_ORIGINS: "https://yunnan-unfolded.github.io,https://yunnanunfolded.com,https://www.yunnanunfolded.com,http://localhost:3000,http://127.0.0.1:3000,http://192.168.3.10:3000";
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESEND_FROM_EMAIL" | "INQUIRY_TO_EMAIL" | "ALLOWED_ORIGINS" | "RESEND_API_KEY">> {}
}
