import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import test from 'node:test';
import {chromium} from 'playwright';
const base=process.env.HOME_CMS_TEST_BASE_URL;
const apiUrl=process.env.HOME_CMS_TEST_API_URL;
const groups={oldRoads:'7. The Old Roads of Yunnan 卡片图片',southGreen:'8. South into the Green 卡片图片'};
test('Homepage example card photos save via Tina and restore without content or layout changes',{timeout:180000,skip:!base||!apiUrl},async()=>{
 const original=JSON.parse(readFileSync('content/home/home.json','utf8'));
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:960}});
 await context.route('**/*',route=>{const r=route.request(),u=new URL(r.url());return r.method()==='POST'&&!(u.href===new URL(apiUrl).href)?route.abort():route.continue();});
 const admin=await context.newPage(),page=await context.newPage();const errors=[],evidence={saves:[],checks:[]};page.on('pageerror',e=>errors.push(e.message));
 mkdirSync('artifacts/home-example-images',{recursive:true});let current;let baseline;
 async function group(key){if(current)await admin.getByRole('button',{name:'home',exact:true}).click();await admin.getByRole('button',{name:groups[key],exact:true}).click();await admin.locator(`[id="${key}.src-path"]`).waitFor();current=key;}
 async function save(){const result=admin.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/graphql'&&r.request().postData()?.includes('mutation'));await admin.getByRole('button',{name:'Save',exact:true}).click();const r=await result;assert.equal(r.status(),200);assert.ok(!(await r.json()).errors);await admin.waitForFunction(()=>[...document.querySelectorAll('button')].some(b=>b.textContent==='Save'&&b.disabled));evidence.saves.push({field:current,status:200});}
 async function content(){return page.locator('.journey-card').evaluateAll(cards=>cards.map(c=>({text:c.innerText,links:[...c.querySelectorAll('a')].map(a=>a.getAttribute('href'))})));}
 async function check(values,label){for(const width of [1440,390,430]){await page.setViewportSize({width,height:960});await page.goto(base,{waitUntil:'networkidle'});assert.deepEqual(await content(),baseline);for(const [i,key] of ['oldRoads','southGreen'].entries()){const img=page.locator('.journey-card img').nth(i+1);await img.scrollIntoViewIfNeeded();await img.evaluate(i=>i.decode());assert.equal(await img.evaluate(i=>i.currentSrc),new URL(values[key].src,base).href);assert.equal(await img.getAttribute('alt'),values[key].alt);assert.equal(await img.evaluate(i=>getComputedStyle(i).objectFit),'cover');}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.journey-card').nth(1).scrollIntoViewIfNeeded();await page.screenshot({path:`artifacts/home-example-images/${label}-${width}.png`});evidence.checks.push({label,width,overflow:false,contentUnchanged:true});}}
 try{await page.goto(base,{waitUntil:'networkidle'});baseline=await content();await admin.goto(base+'/admin/index.html#/collections/edit/home/home');await admin.getByRole('button',{name:'Enter Edit Mode',exact:true}).click();const tests={oldRoads:'/images/journeys/yunnan-slowly/laoyao-mountain-rhododendron-hiker-1600.webp',southGreen:'/images/about/chloe-rhododendrons.webp'};for(const key of Object.keys(tests)){await group(key);assert.equal(await admin.locator('select').count(),0);await admin.locator(`[id="${key}.src-path"]`).fill(tests[key]);await admin.locator(`[id="${key}.src-path"]`).blur();await save();}await check({...original,oldRoads:{...original.oldRoads,src:tests.oldRoads},southGreen:{...original.southGreen,src:tests.southGreen}},'test');}
 finally{try{if(current){for(const key of ['oldRoads','southGreen']){await group(key);await admin.locator(`[id="${key}.src-path"]`).fill(original[key].src);await admin.locator(`[id="${key}.src-path"]`).blur();if(!await admin.getByRole('button',{name:'Save',exact:true}).isDisabled())await save();}assert.deepEqual(JSON.parse(readFileSync('content/home/home.json','utf8')),original);await check(original,'restored');evidence.restored=true;}assert.deepEqual(errors,[]);}finally{evidence.errors=errors;writeFileSync('artifacts/home-example-images/evidence.json',JSON.stringify(evidence,null,2));await browser.close();}}
});
